from __future__ import annotations

from typing import Callable
from .server_browser_sources import (
    BrowserSource,
    all_browser_source,
    imported_source_browser_source,
    is_filtered_source,
    person_browser_source,
    source_item_url,
    source_month_url,
    source_year_url,
)
from .server_browser_sidecars import (
    clear_sidecar_data_caches,
    hidden_sidecar_file_ids_for_day,
    hidden_sidecar_main_image,
    motion_video_file_ids,
    motion_video_for_image,
    motion_video_main_image,
    original_filename_for_item,
    query_motion_video_file_ids,
    query_motion_video_file_ids_for_day,
    query_raw_sidecar_file_ids,
    query_raw_sidecar_file_ids_for_day,
    query_raw_sidecar_ids_by_image_id,
    raw_sidecar_file_ids,
    raw_sidecar_for_image,
    raw_sidecar_group_keys,
    raw_sidecar_groups,
    raw_sidecar_id_by_image_id,
    raw_sidecar_ids_by_image_id,
    raw_sidecar_image_id_by_sidecar_id,
    raw_sidecar_main_image,
    source_parent_path_key,
)
from .server_browser_queries import (
    active_item_by_id_including_hidden,
    adjacent_browser_items,
    adjacent_person_items,
    adjacent_items_from_id_order,
    adjacent_items_from_list,
    adjacent_source_items,
    adjacent_sql_filtered_source_items,
    adjacent_unfiltered_source_items,
    all_source_items,
    all_source_where,
    attach_face_database,
    attach_source_sql_filter_databases,
    browser_date_for_item,
    browser_item_by_id,
    browser_item_ids,
    browser_month_items,
    browser_month_keys,
    browser_month_navigation,
    browser_month_navigation_for_key,
    browser_year_cards,
    browser_year_month_cards,
    browser_year_summaries,
    filter_motion_video_items,
    filter_out_of_focus_items,
    first_browser_item,
    first_month_in_year,
    first_source_day_item,
    first_source_item,
    first_sql_filtered_source_day_item,
    first_sql_filtered_source_item,
    first_unfiltered_source_day_item,
    first_unfiltered_source_item,
    first_year_thumbnail_item_id,
    hidden_sidecar_id_filter_sql,
    image_extension_sql,
    imported_source_by_id,
    imported_source_items,
    is_image_item,
    item_by_id,
    item_order_key,
    items_by_file_ids,
    last_month_before_year,
    manual_date_midpoint_for_item,
    month_key_for_item,
    month_key_from_stored_path,
    month_navigation_for_keys,
    next_month_key,
    out_of_focus_file_ids,
    parse_iso_date,
    person_item_by_id,
    person_month_items,
    person_month_navigation,
    representative_image_item,
    should_filter_out_of_focus,
    source_item_by_id,
    source_item_count,
    source_item_ids,
    source_items,
    source_month_items,
    source_month_keys,
    source_month_navigation,
    source_month_navigation_for_key,
    source_summary_rows,
    source_year_cards,
    source_year_month_cards,
    source_shows_motion_videos,
    sql_filtered_source_item_by_id,
    sql_filtered_source_item_count,
    sql_filtered_source_item_ids,
    sql_filtered_source_month_items,
    sql_filtered_source_month_keys,
    tagged_items,
    unfiltered_source_item_by_id,
    valid_day_key,
    valid_month_key,
    valid_year_key,
    with_motion_video_filter,
    with_out_of_focus_filter,
)
from .server_browser_info_html import (
    camera_text_from_item,
    date_source_text,
    display_short_date,
    format_uncertainty_days,
    google_maps_link_html,
    google_maps_url,
    gps_coordinate_pair,
    gps_location_badge_html,
    gps_source_is_manual_h3,
    gps_source_text,
    image_date_text,
    image_geo_area_links_html,
    image_info_content_html,
    image_info_rows,
    image_source_rows,
    image_tag_links_html,
    info_row_html,
    manual_date_text,
    manual_h3_badge_html,
    manual_h3_cell,
    manual_h3_cell_name,
    manual_h3_label_html,
    manual_h3_link_html,
    manual_h3_place_name,
    manual_h3_status_html,
    optional_item_value,
)
from .server_browser_admin_html import (
    source_row_html,
    sources_page_html,
    tag_row_actions_html,
    tag_row_html,
    tags_page_html,
)
from .server_browser_overview_html import (
    empty_browser_html,
    empty_person_browser_html,
    empty_source_html,
    empty_source_message,
    month_page_html,
    person_month_page_html,
    person_not_found_html,
    source_month_breadcrumb_html,
    source_month_item_html,
    source_month_page_html,
    source_year_breadcrumb_html,
    source_year_card_html,
    source_year_navigation_controls_html,
    source_year_months_page_html,
    source_years_navigation_controls_html,
    source_years_page_html,
    thumbnail_media_html,
    year_card_html,
    year_month_card_html,
    year_months_page_html,
    year_navigation_controls_html,
    years_navigation_controls_html,
    years_page_html,
)
from .server_browser_item_html import (
    active_tag_name_keys_for_file,
    all_browser_item_link,
    associated_file_button_html,
    associated_file_buttons_html,
    associated_files_for_item,
    breadcrumb_html,
    clear_tag_control_rows_cache,
    delete_button_html,
    hidden_after_out_of_focus_tag_redirect_url,
    hotkey_date_hint_text,
    hotkey_hint_label,
    hotkey_hints_panel_html,
    image_info_overlay_html,
    item_media_html,
    item_media_width_height_ratio,
    item_page_html,
    item_side_panel_html,
    item_string_value,
    item_view_rotation,
    manual_date_button_html,
    manual_date_overlay_html,
    media_link_class_attr,
    person_item_page_html,
    previous_month_overview_url,
    previous_year_overview_url,
    remove_manual_location_button_html,
    rotation_buttons_html,
    rotation_style_attr,
    source_breadcrumb_label,
    source_item_breadcrumb_html,
    source_item_media_html,
    source_item_page_html,
    suggestion_toggle_href,
    tag_control_rows,
    _source_item_controls_html,
    _source_item_face_html,
    _source_item_header_html,
    _source_item_side_panel_html,
)

_SOURCE_REEXPORTS = (
    BrowserSource,
    all_browser_source,
    imported_source_browser_source,
    is_filtered_source,
    person_browser_source,
    source_item_url,
    source_month_url,
    source_year_url,
)

_SIDECAR_REEXPORTS = (
    hidden_sidecar_file_ids_for_day,
    hidden_sidecar_main_image,
    motion_video_file_ids,
    motion_video_for_image,
    motion_video_main_image,
    original_filename_for_item,
    query_motion_video_file_ids,
    query_motion_video_file_ids_for_day,
    query_raw_sidecar_file_ids,
    query_raw_sidecar_file_ids_for_day,
    query_raw_sidecar_ids_by_image_id,
    raw_sidecar_file_ids,
    raw_sidecar_for_image,
    raw_sidecar_group_keys,
    raw_sidecar_groups,
    raw_sidecar_id_by_image_id,
    raw_sidecar_ids_by_image_id,
    raw_sidecar_image_id_by_sidecar_id,
    raw_sidecar_main_image,
    source_parent_path_key,
)

_QUERY_REEXPORTS = (
    active_item_by_id_including_hidden,
    adjacent_browser_items,
    adjacent_items_from_id_order,
    adjacent_items_from_list,
    adjacent_person_items,
    adjacent_source_items,
    adjacent_sql_filtered_source_items,
    adjacent_unfiltered_source_items,
    all_source_items,
    all_source_where,
    attach_face_database,
    attach_source_sql_filter_databases,
    browser_date_for_item,
    browser_item_by_id,
    browser_item_ids,
    browser_month_items,
    browser_month_keys,
    browser_month_navigation,
    browser_month_navigation_for_key,
    browser_year_cards,
    browser_year_month_cards,
    browser_year_summaries,
    filter_motion_video_items,
    filter_out_of_focus_items,
    first_browser_item,
    first_month_in_year,
    first_source_day_item,
    first_source_item,
    first_sql_filtered_source_day_item,
    first_sql_filtered_source_item,
    first_unfiltered_source_day_item,
    first_unfiltered_source_item,
    first_year_thumbnail_item_id,
    hidden_sidecar_id_filter_sql,
    image_extension_sql,
    imported_source_by_id,
    imported_source_items,
    is_image_item,
    item_by_id,
    item_order_key,
    items_by_file_ids,
    last_month_before_year,
    manual_date_midpoint_for_item,
    month_key_for_item,
    month_key_from_stored_path,
    month_navigation_for_keys,
    next_month_key,
    out_of_focus_file_ids,
    parse_iso_date,
    person_item_by_id,
    person_month_items,
    person_month_navigation,
    representative_image_item,
    should_filter_out_of_focus,
    source_item_by_id,
    source_item_count,
    source_item_ids,
    source_items,
    source_month_items,
    source_month_keys,
    source_month_navigation,
    source_month_navigation_for_key,
    source_summary_rows,
    source_year_cards,
    source_year_month_cards,
    source_shows_motion_videos,
    sql_filtered_source_item_by_id,
    sql_filtered_source_item_count,
    sql_filtered_source_item_ids,
    sql_filtered_source_month_items,
    sql_filtered_source_month_keys,
    tagged_items,
    unfiltered_source_item_by_id,
    valid_day_key,
    valid_month_key,
    valid_year_key,
    with_motion_video_filter,
    with_out_of_focus_filter,
)

_ITEM_HTML_REEXPORTS = (
    active_tag_name_keys_for_file,
    all_browser_item_link,
    associated_file_button_html,
    associated_file_buttons_html,
    associated_files_for_item,
    breadcrumb_html,
    delete_button_html,
    hidden_after_out_of_focus_tag_redirect_url,
    hotkey_date_hint_text,
    hotkey_hint_label,
    hotkey_hints_panel_html,
    image_info_overlay_html,
    item_media_html,
    item_media_width_height_ratio,
    item_page_html,
    item_side_panel_html,
    item_string_value,
    item_view_rotation,
    manual_date_button_html,
    manual_date_overlay_html,
    media_link_class_attr,
    person_item_page_html,
    previous_month_overview_url,
    previous_year_overview_url,
    remove_manual_location_button_html,
    rotation_buttons_html,
    rotation_style_attr,
    source_breadcrumb_label,
    source_item_breadcrumb_html,
    source_item_media_html,
    source_item_page_html,
    suggestion_toggle_href,
    tag_control_rows,
    _source_item_controls_html,
    _source_item_face_html,
    _source_item_header_html,
    _source_item_side_panel_html,
)


_INFO_HTML_REEXPORTS = (
    camera_text_from_item,
    date_source_text,
    display_short_date,
    format_uncertainty_days,
    google_maps_link_html,
    google_maps_url,
    gps_coordinate_pair,
    gps_location_badge_html,
    gps_source_is_manual_h3,
    gps_source_text,
    image_date_text,
    image_geo_area_links_html,
    image_info_content_html,
    image_info_rows,
    image_source_rows,
    image_tag_links_html,
    info_row_html,
    manual_date_text,
    manual_h3_badge_html,
    manual_h3_cell,
    manual_h3_cell_name,
    manual_h3_label_html,
    manual_h3_link_html,
    manual_h3_place_name,
    manual_h3_status_html,
    optional_item_value,
)


_ADMIN_HTML_REEXPORTS = (
    source_row_html,
    sources_page_html,
    tag_row_actions_html,
    tag_row_html,
    tags_page_html,
)

_OVERVIEW_HTML_REEXPORTS = (
    empty_browser_html,
    empty_person_browser_html,
    empty_source_html,
    empty_source_message,
    month_page_html,
    person_month_page_html,
    person_not_found_html,
    source_month_breadcrumb_html,
    source_month_item_html,
    source_month_page_html,
    source_year_breadcrumb_html,
    source_year_card_html,
    source_year_navigation_controls_html,
    source_year_months_page_html,
    source_years_navigation_controls_html,
    source_years_page_html,
    thumbnail_media_html,
    year_card_html,
    year_month_card_html,
    year_months_page_html,
    year_navigation_controls_html,
    years_navigation_controls_html,
    years_page_html,
)


ShellPageRenderer = Callable[..., str]
PageRenderer = Callable[[str, str], str]
Breadcrumb = tuple[str, str | None] | tuple[str, str | None, str | None]
MONTH_NAMES = {
    "01": "Januar",
    "02": "Februar",
    "03": "Mars",
    "04": "April",
    "05": "Mai",
    "06": "Juni",
    "07": "Juli",
    "08": "August",
    "09": "September",
    "10": "Oktober",
    "11": "November",
    "12": "Desember",
}
def clear_sidecar_caches() -> None:
    clear_sidecar_data_caches()
    clear_tag_control_rows_cache()







